### ISSUE TITLE
Review Airtable abstract submissions and finalize projects/workshops selection

### ISSUE THREAD

**Issue by PaulaPaul** [anitab-org/2024-GHC-OSD#9]

**Comment by PaulaPaul** [comment]
We've accepted nine OSD teams, and our target is 12:

- (Eclipse](https://github.com/eclipse/eclipse-collections-kata): Confirmed
- [Wildfly-elytron](https://github.com/wildfly-security/wildfly-elytron): not confirmed
- [OpenJS Foundation](https://docs.google.com/presentation/d/1eLdBCHaWUuSpRUj-eZJ3Wog4ZV-Iaqc-qGf85wveLKc/edit#slide=id.g2c4e1c41dca_0_62): Confirmed
- [Azure PyRIT]((https://github.com/Azure/PyRIT): Confirmed
- [Open Data Hub](https://github.com/opendatahub-io): not confirmed - does anyone have a contact here?
- [FINOS](https://github.com/opendatahub-io): not confirmed - main contact is traveling, Paula is working with Tamera and an alternate
- [Undertow](https://github.com/undertow-io/undertow): Confirmed
- [LF AI & Data](https://github.com/lfai) Still not confirmed: Vini do you have a contact here?
- [CHAOSS](https://github.com/chaoss) Confirmed

Of the remaining abstracts, we would like to choose three or four, to round the field out to twelve or at most 13 teams/groups:

1. Airtable tag R_40rxlxuOXE0SL6s : Half Day Workshop
  - Architecting the Future: Leveraging Apache Kafka for Real-Time, Scalable Data Pipelines
  - "Architecting the Future: Leveraging Apache Kafka for Real-Time, Scalable Data Pipelines" is a dynamic, half-day workshop designed for those eager to master Kafka with Go for building high-performance data systems. It combines theory with practical exercises, covering Kafka setup, message processing, stream processing, and building microservices with Go. Attendees will learn through producing and consuming messages, optimizing performance, and troubleshooting, culminating in the ability to architect scalable, fault-tolerant streaming solutions. Ideal for software developers and data engineers, this workshop requires a laptop, Go, and Kafka installation. Gain hands-on experience and insights to innovate in real-time data processing and event-driven architectures.

2. Aitrable tag R_2r1H5Co2sDm6C1G: [Open Source Security Foundation DevRel Community](https://github.com/ossf/devRel-community/)

3. Airtable tag R_6ieTZX0h7KCs31i: [Intel Retail Automated Self Checkout](https://github.com/intel-retail/automated-self-checkout)

4. Airtable tag R_32cn5zybdD1n2C9: [McKinsey Vizro](https://github.com/mckinsey/vizro)

5. Airtable tag R_3DSU9fCHHvMKQUx: [Google's Ruy Wang - PerfKitBenchmarker - DevOps](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker)

6. Airtable tag  R_4QilnGly1o5JIDn: [Appwrite](https://github.com/appwrite/appwrite)

7. Airtable tag R_3jp5u1CYLxpu334: [Hats for Cats workshop - requires PowerPoint](https://github.com/sruthisoorian/HatsForCats)

**Comment by PaulaPaul** [comment]
Paula's votes are to accept:
- 3
- 4
- 5
- 6

If all four accept we will have 13 projects

It might be good to accept the first one as well (number 1) and run that as a concurrent half day workshop once in the morning and again in the afternoon?

**Comment by gkimbwala** [comment]
My favorites are as follows:
2
4
5
6

**Comment by vinijaiswal** [comment]
Here are some of my votes:
1
4
5
6

Also, I confirm the participation from LF AI and Data. Thanks!
